# Generated by Django 2.1.5 on 2019-03-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
